// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/dadyutenga/hms-control/internal/views/layout"

type LoginProps struct {
	Error    string
	Verified bool
}

func Login(props LoginProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header style=\"background-color: var(--color-bg); border-bottom: 1px solid var(--color-border); box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);\"><div class=\"flex items-center justify-between max-w-[1120px] mx-auto h-16 px-6\"><div class=\"text-xl font-bold tracking-tight\" style=\"color: var(--color-fg); font-family: var(--font-heading);\">Hotel Management System</div><nav class=\"hidden md:flex items-center space-x-8 h-full\"><a class=\"transition text-sm font-medium flex items-center h-full\" style=\"color: var(--color-muted-fg); font-family: var(--font-heading);\" href=\"/\">Home</a> <a class=\"border-b-2 font-semibold flex items-center h-full text-sm\" style=\"border-color: var(--color-fg); color: var(--color-fg); font-family: var(--font-heading);\" href=\"/login\">Login</a> <a class=\"transition text-sm font-medium flex items-center h-full\" style=\"color: var(--color-muted-fg); font-family: var(--font-heading);\" href=\"/register\">Register</a></nav></div></header><main class=\"flex items-center justify-center min-h-[80vh] px-6\"><div class=\"w-full max-w-md\"><div style=\"background-color: var(--color-bg); border: 1px solid var(--color-border); padding: 2rem; border-radius: 0.75rem; box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);\"><h1 class=\"text-2xl font-bold mb-6 text-center\" style=\"color: var(--color-fg); font-family: var(--font-heading);\">Login to Hotel Management System</h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Verified {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"mb-4 p-3 rounded text-sm flex items-center gap-2\" style=\"background-color: color-mix(in srgb, var(--color-brand-blue) 8%, var(--color-bg)); border: 1px solid color-mix(in srgb, var(--color-brand-blue) 25%, var(--color-border)); color: var(--color-brand-blue);\"><span class=\"material-symbols-outlined text-base\">check_circle</span> Email verified successfully! You can now log in.</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.Error != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"mb-4 p-3 rounded text-sm flex items-center gap-2\" style=\"background-color: color-mix(in srgb, var(--color-destructive) 8%, var(--color-bg)); border: 1px solid color-mix(in srgb, var(--color-destructive) 25%, var(--color-border)); color: var(--color-destructive);\"><span class=\"material-symbols-outlined text-base\">error</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Error)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/auth/login.templ`, Line: 35, Col: 20}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<form method=\"POST\" action=\"/login\" class=\"space-y-4\"><div class=\"flex flex-col gap-2\"><label class=\"text-sm font-semibold\" style=\"color: var(--color-fg);\" for=\"email\">Email</label> <input style=\"border: 1px solid var(--color-border); border-radius: 0.5rem; padding: 0.75rem; outline: none; transition: all 0.2s;\" class=\"focus:ring-1 outline-none transition\" type=\"email\" name=\"email\" required placeholder=\"you@company.co.tz\"></div><div class=\"flex flex-col gap-2\"><label class=\"text-sm font-semibold\" style=\"color: var(--color-fg);\" for=\"password\">Password</label> <input style=\"border: 1px solid var(--color-border); border-radius: 0.5rem; padding: 0.75rem; outline: none; transition: all 0.2s;\" class=\"focus:ring-1 outline-none transition\" type=\"password\" name=\"password\" required placeholder=\"Your password\"></div><button class=\"w-full py-3 text-sm font-semibold hover:opacity-90 transition flex items-center justify-center gap-2 btn btn-primary\" style=\"background-color: var(--color-fg); color: var(--color-primary-fg); border-radius: 9999px;\" type=\"submit\"><span class=\"material-symbols-outlined text-base\">login</span> Sign In</button></form><p class=\"mt-6 text-center text-sm\" style=\"color: var(--color-muted-fg);\">Don't have an account? <a href=\"/register\" class=\"hover:underline font-semibold\" style=\"color: var(--color-brand-blue);\">Register here</a></p></div></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Login").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
