// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/dadyutenga/hms-control/internal/views/layout"
)

func SMTPSettingsPage(settings map[string]string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-3xl mx-auto p-6\"><h1 class=\"text-2xl font-bold mb-6\" style=\"color: var(--color-fg); font-family: var(--font-heading);\">SMTP Settings</h1><form method=\"POST\" action=\"/admin/settings/smtp\" class=\"space-y-4\"><div><label style=\"color: var(--color-muted-fg); font-size:0.875rem;\">SMTP Host</label> <input type=\"text\" name=\"smtp_host\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(settings["smtp_host"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/admin/smtp_settings.templ`, Line: 14, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"w-full rounded-lg border px-3 py-2 text-sm\" style=\"border-color: var(--color-border); background: var(--color-bg); color: var(--color-fg);\"></div><div><label style=\"color: var(--color-muted-fg); font-size:0.875rem;\">SMTP Port</label> <input type=\"text\" name=\"smtp_port\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(settings["smtp_port"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/admin/smtp_settings.templ`, Line: 18, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"w-full rounded-lg border px-3 py-2 text-sm\" style=\"border-color: var(--color-border); background: var(--color-bg); color: var(--color-fg);\"></div><div><label style=\"color: var(--color-muted-fg); font-size:0.875rem;\">SMTP User</label> <input type=\"text\" name=\"smtp_user\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(settings["smtp_user"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/admin/smtp_settings.templ`, Line: 22, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"w-full rounded-lg border px-3 py-2 text-sm\" style=\"border-color: var(--color-border); background: var(--color-bg); color: var(--color-fg);\"></div><div><label style=\"color: var(--color-muted-fg); font-size:0.875rem;\">SMTP Password (leave blank to keep current)</label> <input type=\"password\" name=\"smtp_pass\" class=\"w-full rounded-lg border px-3 py-2 text-sm\" style=\"border-color: var(--color-border); background: var(--color-bg); color: var(--color-fg);\"></div><div><label style=\"color: var(--color-muted-fg); font-size:0.875rem;\">From Address</label> <input type=\"text\" name=\"smtp_from\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(settings["smtp_from"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/admin/smtp_settings.templ`, Line: 30, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"w-full rounded-lg border px-3 py-2 text-sm\" style=\"border-color: var(--color-border); background: var(--color-bg); color: var(--color-fg);\"></div><div class=\"flex gap-3\"><button type=\"submit\" class=\"btn btn-primary\" style=\"height:2.5rem;padding:0 1.5rem;font-size:0.875rem;\">Save Settings</button> <button type=\"button\" onclick=\"testSMTP()\" class=\"btn btn-outline\" style=\"height:2.5rem;padding:0 1.5rem;font-size:0.875rem;\">Test SMTP</button></div></form><div id=\"smtp-test-result\" class=\"mt-4\"></div></div><script>\n\t\t\tfunction testSMTP() {\n\t\t\t\tvar email = prompt('Enter test email address:');\n\t\t\t\tif (!email) return;\n\t\t\t\tvar result = document.getElementById('smtp-test-result');\n\t\t\t\tresult.textContent = 'Sending test...';\n\t\t\t\tfetch('/admin/settings/smtp/test', {\n\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\theaders: { 'Content-Type': 'application/x-www-form-urlencoded' },\n\t\t\t\t\tbody: 'test_email=' + encodeURIComponent(email)\n\t\t\t\t})\n\t\t\t\t.then(r => r.json())\n\t\t\t\t.then(d => {\n\t\t\t\t\tresult.textContent = d.ok ? 'Test email sent successfully!' : 'Error: ' + d.error;\n\t\t\t\t\tresult.style.color = d.ok ? 'hsl(140, 60%, 40%)' : 'hsl(0, 70%, 40%)';\n\t\t\t\t});\n\t\t\t}\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("SMTP Settings").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
